### ISSUE TITLE
How to follow up?

### ISSUE THREAD

**Issue by SergioCrisostomo** [tailwindlabs/tailwindui-vue#10]
Hi folks, I am curious about the project and wonder how to contribute. 
Code in the Readme example is broken, the example code is not Vue 3 compatible, there is no dev environment, I see no live demo or other resources.

But I see PRs comming in, and 431(!! 😮 ) stars on 7 commits... I feel there is a party going on but I can't see it 🤔 

Question: where can I find the current dev environment, roadmap, known issues, etc? Is this repo open for contributors?

**Comment by herpaderpaldent** [comment]
watch it get amazed: https://www.youtube.com/watch?v=fx2lbOCAqrg&feature=youtu.be

**Comment by SergioCrisostomo** [comment]
@herpaderpaldent thanks, will check 👍
