### ISSUE TITLE
Cannot read property 'scrollIntoView' of undefined"

### ISSUE THREAD

**Issue by amrap030** [tailwindlabs/tailwindui-vue#12]
Hello,

I was following along your recent youtube video but I am always getting the following error:

[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'scrollIntoView' of undefined"

<img width="1143" alt="Bildschirmfoto 2020-06-14 um 04 16 33" src="https://user-images.githubusercontent.com/35061229/84583173-0c692980-adf6-11ea-9639-36dbfbbc0c54.png">

I did everything like you, in the ListboxOption I set the key to the id of the object and the value to the id of the object as well but I am still getting this error message. In the video you got the same error that was fixed by setting the key and value to the object id's.

How can I get rid of it?

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
