### ISSUE TITLE
Any plans for searchable components, ie combobox and autocomplete/typeahead?

### ISSUE THREAD

**Issue by ragulka** [tailwindlabs/tailwindui-vue#13]
I just watched the screencast where this was introduced (https://www.youtube.com/watch?v=fx2lbOCAqrg) and I'm very excited for this! The premise of being able to use 100% my own markup and styles really is key here.

Are there any plans to add ComboBox (basically a select which allows filtering the options & typing a custom value as well) and Autocomplete/Typeahead functionality? I seems like the Listbox already has a simple typeahead built-in to shift the active element based on keyboard input (much like native selects), which can serve as a starting point, perhaps.

However, there are some limitations with it:
* there doesn't seem to be a direct way to customize the options filter (https://github.com/tailwindui/vue/blob/master/src/Listbox.js#L290-L292) - unless we can override the `type` method?
* typehead value is automatically cleared after user stops typing (wouldn't work for combobox or autocomplete)

For background: I need to use ComboBox and Autocomplete components in my project and I initially tried to use them from Vuetify (https://vuetifyjs.com/en/components/combobox/ and https://vuetifyjs.com/en/components/autocompletes/). While the interactions etc are just what I would expect, I don't want to include the whole library in my project, nor do I care for their markup and styles (SCSS).

So I set out to build my own custom components (largely following your Advanced Vue Component Design course). As you noted in the video, it may seem easy on the surface, but there's a ton of effort to actually make these production-ready. This is why I'm again on the lookout for any libraries / packages that would handle most of the heavy lifting, if possible.

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
