### ISSUE TITLE
Direction keys scrolls window.

### ISSUE THREAD

**Issue by woodinteractive** [tailwindlabs/tailwindui-vue#14]
When I drop the basic example from the docs into a vue-cli project and focus the listbox and hit the down arrow, the window scrolls instead of the list opening or items being selected. Any idea why my results are different from the implementation on the YouTube video?

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
