### ISSUE TITLE
Firefox bug - Choosing option reopens the list

### ISSUE THREAD

**Issue by estevanmaito** [tailwindlabs/tailwindui-vue#5]
0.1.0-alpha.0
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"

**Steps to reproduce**
*Using the default example
1. Open the list
2. Select an option using space

It's caused by an old [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1487102) where the space key also triggers a click, so it closes the list and reopens immediately.

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
