### ISSUE TITLE
Is it intentional that mouseleave removes the activeItem in all cases?

### ISSUE THREAD

**Issue by estevanmaito** [tailwindlabs/tailwindui-vue#6]
Right now, if you open the list, pass the mouse over and use the keyboard (enter or space) to select, the button looses the content as there is no `activeItem` selected.

`mouseleave` on `ListboxList` does this [(source)](https://github.com/tailwindui/vue/blob/master/src/Listbox.js#L111): `this.context.activeItem.value = null`

If it's intended, I think there should be an indication that it expects that a placeholder must be present, like:

```vue
<ListboxButton class="rounded p-3 border">
  <span v-if="selectedWrestler">
    {{ selectedWrestler }}
  </span>
  <span v-else>
    Select a wrestler...
  </span>
</ListboxButton>
```

If not, these are some options:

1. Don't null the `activeItem`, so if the person leaves the dropdown and press enter/space, the last item under the mouse would be selected;
2. Close early inside `select` if no value is selected, behaving like an 'Esc';

**Comment by mitchbne** [comment]
Honestly, I think this is intended behaviour. But, I think option 1 is a nice idea.

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
